const GochiActionTypes = {
    SET_CURRENT_ANIMATION: 'SET_CURRENT_ANIMATION',
    TOGGLE_ITEM_VISIBLE: 'TOGGLE_ITEM_VISIBLE',
    SET_CURRENT_ITEM: 'SET_CURRENT_ITEM'
}

export default GochiActionTypes;