const GochiActionTypes = {
    SET_CURRENT_ANIMATION: 'SET_CURRENT_ANIMATION',
    TOGGLE_ITEM_VISIBLE: 'TOGGLE_ITEM_VISIBLE',
    TOGGLE_POOP_VISIBLE: 'TOGGLE_POOP_VISIBLE',
    TOGGLE_ASLEEP: 'TOGGLE_ASLEEP',
    SET_CURRENT_ITEM: 'SET_CURRENT_ITEM',
    TOGGLE_NEED_VISIBLE: 'TOGGLE_NEED_VISIBLE',
    SET_NEED: 'SET_NEED'
}

export default GochiActionTypes;